# Migrate Discord Bot Files Workflow

name: Migrate Discord Bot Files

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout discord-bot-cli-nodejs repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone dita-ot repository
        run: |
          git clone https://github.com/android606/dita-ot.git /tmp/dita-ot

      - name: Copy discord-* folders
        run: |
          # Remove existing discord-* folders if they exist
          rm -rf discord-bot-cli discord-bot-cli-js
          
          # Copy discord-* folders from dita-ot to current repository
          if [ -d "/tmp/dita-ot/discord-bot-cli" ]; then
            cp -R /tmp/dita-ot/discord-bot-cli .
            echo "Copied discord-bot-cli"
          fi
          
          if [ -d "/tmp/dita-ot/discord-bot-cli-js" ]; then
            cp -R /tmp/dita-ot/discord-bot-cli-js .
            echo "Copied discord-bot-cli-js"
          fi

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add discord-bot-cli discord-bot-cli-js
          git commit -m "Sync discord-* folders from dita-ot repository"
          git push