# Migrating Files Workflow

name: Migrate Files

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Run migration script
        run: |
          npm run migrate

      - name: Copy files
        run: |
          cp -R ./source/path/. ./destination/path/
          # Ensure to replace the source and destination with actual paths

      - name: Commit migrated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Migrated files" || echo "No changes to commit"